kind: pipeline
name: default

steps:
- name: frontend
  image: node
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY:
      from_secret: AWS_SECRET_ACCESS_KEY
  commands:
  - npm install
  - npm run build && npm run deploy
